server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhuche?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
        format_sql: true
        ddl-auto: create-drop