server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhuche?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: none